### PR TITLE
replace jq with yq

### LINKED ISSUE #253: rules_oci does not work on linux arm64 hosts due to jq dependency
```
While resolving toolchains for target //bin/services/external_proxy:image: No matching toolchains found for types @aspect_bazel_lib//lib:jq_toolchain_type.
To debug, rerun with --toolchain_resolution_debug='@aspect_bazel_lib//lib:jq_toolchain_type'
If platforms or toolchains are a new concept for you, we'd encourage reading https://bazel.build/concepts/platforms-intro.
```

`//bin/services/external_proxy:image` being a `oci_image` target

if this is a known issue perhaps stating compatible architectures might be handy

### PR DESCRIPTION
**Pull request by archen**
The `jq` toolchain does not support as many architectures as `yq` and `yq` supports (for the most-part) a super-set of the `jq` capabilities. This change introduces the use of `yq` as a `jq` replacement for downstream users with build-worker architectures not natively supported by `jq`.

fixes: https://github.com/bazel-contrib/rules_oci/issues/253

requires: https://github.com/aspect-build/bazel-lib/pull/456

```starlark
# WORKSPACE
load("@bazel_tools//tools/build_defs/repo:utils.bzl", "maybe")
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
maybe(
    git_repository,
    name = "aspect_bazel_lib",
    commit = "794df714d7efbf5f2b986470428bea311f4fd772",
    remote = "https://github.com/aspect-build/bazel-lib",
    shallow_since = "1687478984 -0700",
)

maybe(
    git_repository,
    name = "rules_oci",
    remote = "https://github.com/archen/rules_oci",
    commit = "7700f626ad3439a51e9735e0fb1c2f69734e8a28",
    shallow_since = "1688397071 -0400",
)
```

With the updated rules loaded, you can also `stamp` images with the following modification:
```starlark
"""Helper for stamping version control info into OCI image tags

Modified from: https://github.com/bazel-contrib/rules_oci/blob/e426977dcf6bba3017cdc6bb8b1aeca7bc35b1d5/examples/push/stamp_tags.bzl
"""

load("@aspect_bazel_lib//lib:yq.bzl", "yq")
load("@bazel_skylib//lib:types.bzl", "types")

def stamp_tags(name, remote_tags, **kwargs):
    """Wrapper macro around the [yq](https://docs.aspect.build/rules/aspect_bazel_lib/docs/yq) rule.

    Produces a text file that can be used with the `remote_tags` attribute of [`oci_push`](#oci_push).

    Each entry in `remote_tags` is typically either a constant like `my-repo:latest`, or can contain a stamp expression.
    The latter can use any key from `bazel-out/stable-status.txt` or `bazel-out/volatile-status.txt`.
    See https://docs.aspect.build/rules/aspect_bazel_lib/docs/stamping/ for details.

    The yq `//` default operator is useful for returning an alternative value for unstamped builds.

    For example, if you use the expression `($stamp.BUILD_EMBED_LABEL // "0.0.0")`, this resolves to
    "0.0.0" if stamping is not enabled. When built with `--stamp --embed_label=1.2.3` it will
    resolve to `1.2.3`.

    Args:
        name: name of the resulting yq target.
        remote_tags: list of yq expressions which result in a string value, see docs above
        **kwargs: additional named parameters to the yq rule.
    """
    if not types.is_list(remote_tags):
        fail("remote_tags should be a list")

    _maybe_quote = lambda x: x if "\"" in x else "\"{}\"".format(x)
    yq(
        name = name,
        srcs = [],
        outs = ["_{}.tags.txt".format(name)],
        expression = "|".join([
            "load(strenv(STAMP)) as $stamp",
            ",".join([_maybe_quote(t) for t in remote_tags]),
        ]),
        **kwargs
    )
```

### CODE REVIEW

**Comment by hgad** [comment]
Would love to test this locally to validate that it's working as expected (and to use it while the PR is open).

@archen how do you typically override the remote rules_oci repo with a local patched repo?

**Comment by archen** [comment]
@hgad with the workspace snippet included in my PR descriptions

**Comment by archen** [comment]
Or if checked out locally with a local_repository rule, usually for testing/dev

**Comment by hgad** [comment]
Nice, thanks! Will give it a try and report back.

**Comment by archen** [comment]
Great, thanks for giving it a whirl!

**Comment by malt3** [comment]
[aspect-lib v1.33.0 was released](https://github.com/aspect-build/bazel-lib/releases/tag/v1.33.0) and it includes the yq stamping feature.
You'll need to update `aspect_bazel_lib`:

https://github.com/archen/rules_oci/blob/ed776359d69e2a1a95d2482bb9a7aec287642b0f/oci/dependencies.bzl#L30-L35

https://github.com/archen/rules_oci/blob/ed776359d69e2a1a95d2482bb9a7aec287642b0f/MODULE.bazel#L9

**Comment by hgad** [comment]
Forgot to mention that the PR had worked perfectly for me.

**Comment by malt3** [comment]
This PR currently targets https://github.com/archen/rules_oci but the proper upstream would be https://github.com/bazel-contrib/rules_oci. This way it will be reviewed by upstream.

**Comment by hgad** [comment]
@archen Mind opening the same PR against https://github.com/bazel-contrib/rules_oci so it can be reviewed? I can also do it myself if you don't have the time.

**Comment by archen** [comment]
done https://github.com/bazel-contrib/rules_oci/pull/331

**Comment by archen** [comment]
nm, I actually Closed that PR. need to rebase first and use my isolated branch instead of the big change here

**Comment by archen** [comment]
and we're back! https://github.com/bazel-contrib/rules_oci/pull/337

**Pull request closed without merging**
